# Generated by Django 5.1.4 on 2024-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0002_author_publisher_question_student_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('html', 'html'), ('css', 'css'), ('javascript', 'javascript'), ('flask', 'flask'), ('react', 'react')], default='python', max_length=100),
        ),
    ]
